export { default as Connect } from "./connect.svg";
export { default as Docs } from "./docs.svg";
export { default as Search } from "./search.svg";
export { default as Tip } from "./tip.svg";
export { default as Account } from "./account.svg";
export { default as RollingWhite } from "./rolling_white.svg";
export { default as NoData } from "./no_data.svg";
export { default as Close } from "./close.svg";
export { default as Copy } from "./copy.svg";
